name: san3a_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  cookie_jar: ^4.0.8
  dartz: ^0.10.1
  device_preview: ^1.3.1
  dio: ^5.9.0
  dio_cookie_manager: ^3.2.0
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  get_it: ^9.0.5
  google_fonts: ^6.3.2
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  pinput: ^6.0.1
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/translations/

flutter_assets:
  assets_path: assets/svgs
  output_path: lib/core/utils
  filename: app_svgs.dart
  field_prefix: null
  classname: AppSvgs

# flutter_assets:
#   assets_path: assets/images
#   output_path: lib/core/utils
#   filename: app_images.dart
#   field_prefix: null
#   classname: AppImages
# flutter_assets:
#   assets_path: assets/animations
#   output_path: lib/core/utils
#   filename: app_animations.dart
#   field_prefix: null
#   classname: AppAnimations
